### ISSUE TITLE
How to load and use in my project

### ISSUE THREAD

**Issue by SelaO** [darde/react-native-sidemenu#3]
Can you please provide docs on how to include and use in my project? 

I tried to copy DrawerMenu.js and render it like in app.js, but I'm getting a lot of errors.

**Comment by darde** [comment]
Hi @SelaOren,

in order to use this boilerplate, you need to have React Native configured in your development environment.  If you want to use some of the components in your project, you should have imported the [React Native Vector Icons](url) library as well. Can you please show us the way you are trying to use?

**Comment by SelaO** [comment]
I solved some of the errors I had, but now I'm getting: 

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8044): UnableToResolveError: Unable to resolve module `../views/About` from `C:\Conv\Conv2\src\components\StartingPage.js

But it's there: 
![image](https://cloud.githubusercontent.com/assets/21977571/26327754/2cebba70-3f49-11e7-975a-faf8c769712f.png)

I basically copied app.js to my starting view: https://pastebin.com/n6ze3rMq

**Comment by darde** [comment]
Can you please show me the "About.js" code?

**Comment by SelaO** [comment]
Here: https://pastebin.com/nXV3enDL, I didn't touch it.

**Comment by darde** [comment]
Ok, let's do a test. Remove all references to "About.js" in your "StartingPage.js", and let me know if the error continues.

**Comment by SelaO** [comment]
I removed `About` and a few more that were causing errors (`Credits`, `Bass`, etc). 

Now I'm getting: 
>RNVectorIconsModule not available, did you properly integrate the module?

But I did follow its instructions by doing `npm install react-native-vector-icons --save` and copying the fonts folder...

Edit: I figured out the problem with the vector icons, now it works: 

![image](https://cloud.githubusercontent.com/assets/21977571/26369382/33d2412e-3ffd-11e7-9355-1fd99583de3c.png)

I also returned those elements that I remove and now they show without errors, but the images don't show up, any idea why?

One more question, if I want just the hamburger button to display the menu, what should I remove and what should I keep?

**Comment by darde** [comment]
Ok.

1. You said: 

"But I did follow its instructions by doing npm install react-native-vector-icons --save and copying the fonts folder... "

Did you do that correctly? It's very common to make mistakes here.  

>Copy the contents in the Fonts folder to android/app/src/main/assets/fonts (note lowercase font folder).  

Did you also make all the steps? https://github.com/oblador/react-native-vector-icons#option-manually-1  
Did you edit correctly the `android/settings.gradle`, `android/app/build.gradle` and `MainApplication.java` files? 

2. Regarding the images: how you are calling your images? Did you modify the way to call the images?  Can you show me a snippet?  

3. I didn't understand what you mean with this question. Is there another way to display the menu?

**Comment by SelaO** [comment]
1. I edited my post later, that's the "Edit:", so I got the icons to not make an error anymore.
2. I didn't modify how the images are being called.
3. see: 
![image](https://cloud.githubusercontent.com/assets/21977571/26373211/502b31ee-4009-11e7-9fad-a9135a530201.png)

I already have a nav bar, and I want just the side menu to show when clicking the button I highlighted, without everything else.

**Comment by darde** [comment]
Ok, well in this case, let me see if I understood.

You have two navbars?

If so, this is not a good practice, this is an anti-pattern. This can cause confuse for the user experience. Please, check the [Material Guide Lines](https://material.io/guidelines/components/toolbars.html#).

If you want to replace the original navbar to your, you should check the [React Native Android Toolbar documentation](https://facebook.github.io/react-native/docs/toolbarandroid.html), because the way to use is a little bit different from the [Icon.ToolbarAndroid](https://github.com/oblador/react-native-vector-icons#usage-with-toolbarandroid).

**Comment by SelaO** [comment]
Of course I don't want two navbars.

I want just the side panel that opens from the side from your example, I want it to open when clicking the button I drew the red square on that's on my navbar.

**Comment by darde** [comment]
Ok, you have to add a "click" event to your button, and assign it a function like that 

`click={this.toggleDrawer}`

In your constructor bind this function:

`this.toggleDrawer = this.toggleDrawer.bind(this);`

Reference the DrawerLayoutAndroid with this:

`ref={(drawerElement) => { this.DRAWER = drawerElement; }}`

And finally, create the function:

```
toggleDrawer() {
    if (this.state.drawerClosed) {
      this.DRAWER.openDrawer();
    } else {
      this.DRAWER.closeDrawer();
    }
}
```
See my [App.js](https://github.com/darde/react-native-sidemenu/blob/master/app/components/App.js) to more clarification.

**Comment by SelaO** [comment]
What I want to achieve is to have the sidebar open up when clicking a button and to have my own views below the navbar, I want my views to be in the red square: 

![image](https://cloud.githubusercontent.com/assets/21977571/26420661/e4f110b0-40cb-11e7-909f-944c3790ad71.png)

An example of a view would be: 
![image](https://cloud.githubusercontent.com/assets/21977571/26420755/52afbb10-40cc-11e7-87c3-7225f528593e.png)

The navbar will be your navbar along with the sidebar.

Can you please point me out on how to do that?

**Comment by darde** [comment]
I don't know your whole code, because of this is a little bit difficult for me understand how your code works. What I can say is:

1. If you are trying to use a [React Native ToolbarAndroid](https://facebook.github.io/react-native/docs/toolbarandroid.html), check the documentation. Check the property "onActionSelected".

2. If you are implementing a React Native Vector Icons Toolbar, check the documentation in https://github.com/oblador/react-native-vector-icons#usage-with-toolbarandroid

If you want, share your code with me in some way, so I will be able to analyze and perhaps help you more.
