### ISSUE TITLE
Passing Value

### ISSUE THREAD

**Issue by ardynugraha** [darde/react-native-sidemenu#7]
Hi! You did a great work and verry helping me.

So, in my project before I show up Home Screen, Login Sceen will appear.

I think this is the stucture: App->ReduxNavigation->AppNavigation->Home

My question is, how I pass USER_ID through App to Home Sceen? let say I would to display 'Welcome "USER_ID"' in Home Screen, and how to pass value between views?

Thanks.

**Comment by darde** [comment]
Hi @ardynugraha, I think there are many ways you can achieve that.

#1 You can pass the USER_ID via params in the [navigate method](https://reactnavigation.org/docs/navigators/navigation-actions#Navigate). 

#2 You can share this info via Redux Store, and get the USER_ID via propTypes from your Home Container.

I'm closing this issue because this is not an issue about the template, this is a question about how to extends this template.

Thanks for your comment.

**Comment by ardynugraha** [comment]
Hi @darde thank you for your answer, you're right, it's not an issue, but I've surfing many times in google and I can't get the answer yet.

I've been read about navigate method and Redux Store too but I still not understand how I put or set params in ReduxNavigation.js and how I get the params value in Home.js
Can you give me an example using your react-native-sidemenu?

Hope you can help.
